coding_task:
  description: >
    Write python code to achieve this: {assignment}
  expected_output: >
    A text file that includes the code iteslf, alogn with the output of the code.
  agent: coder
  output_file: output/code_and_output.txt
